---
swagger: "2.0"
info:
  x-ibm-name: "psgdelaysimulator"
  title: "PSGDelaySimulator"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/api/v1"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  ClientID(Query):
    type: "apiKey"
    description: ""
    in: "query"
    name: "client_id"
  ClientID:
    type: "apiKey"
    description: ""
    in: "header"
    name: "X-IBM-Client-Id"
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - proxy:
        title: "proxy"
        timeout: 60
        verb: "keep"
        cache-response: "protocol"
        cache-ttl: 900
        version: "1.0.0"
        target-url: "https://xlg-fdn-p-psg-apim-test-gt1perf.cfapps-gt1-perf.nam.nsroot.net/demo/delaySimulator"
  phase: "realized"
paths:
  /demo/delaySimulator:
    post:
      responses:
        200:
          description: "200 OK"
definitions: {}
tags: []
security:
- ClientID: []
- ClientID(Query): []
